# Generated by Django 4.1.13 on 2023-11-20 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A',
        ),
    ]
