# Generated by Django 4.1.13 on 2023-11-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
