# Generated by Django 4.1.13 on 2023-11-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='check_in_date',
            field=models.DateField(),
        ),
    ]
